version: "3.8"
services:
    rabbitmq3:
        container_name: "rabbitmq3"
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
    producer:
        build: ./producer
        depends_on:
            - rabbitmq3
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - './producer:/producer'
    